frr defaults traditional
hostname ext2
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.2.2/30
exit
!
! A second, longer path to 203.0.113.0/24 with the same origin AS64510.
route-map TO-RR1 permit 10
 set as-path prepend 64510
exit
!
router bgp 64520
 bgp router-id 10.0.2.2
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 10.0.2.1 remote-as 65000
 !
 address-family ipv4 unicast
  network 203.0.113.0/24
  neighbor 10.0.2.1 route-map TO-RR1 out
 exit-address-family
exit
!
end
