frr defaults traditional
hostname attacker
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.2.2/30
exit
!
interface eth2
 ip address 10.0.3.2/30
exit
!
router bgp 65099
 bgp router-id 10.0.2.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 neighbor 10.0.2.1 remote-as 65000
 neighbor 10.0.2.1 description upstream-router
 neighbor 10.0.3.1 remote-as 65001
 neighbor 10.0.3.1 description edge-router
 !
 address-family ipv4 unicast
  neighbor 10.0.2.1 activate
  neighbor 10.0.2.1 soft-reconfiguration inbound
  neighbor 10.0.3.1 activate
  neighbor 10.0.3.1 soft-reconfiguration inbound
 exit-address-family
exit
!
end
