frr defaults traditional
hostname attacker
log syslog informational
ipv6 forwarding
service integrated-vtysh-config
!
ipv6 route 2001:db8:2121::/48 blackhole
!
interface eth1
 ip address 10.0.2.2/30
 ipv6 address 2001:db8:10:3::2/64
exit
!
interface eth2
 ip address 10.0.3.2/30
 ipv6 address 2001:db8:10:4::2/64
exit
!
router bgp 65099
 bgp router-id 10.0.2.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 neighbor 10.0.2.1 remote-as 65000
 neighbor 10.0.2.1 description upstream-router
 neighbor 10.0.3.1 remote-as 65001
 neighbor 10.0.3.1 description edge-router
 neighbor 2001:db8:10:3::1 remote-as 65000
 neighbor 2001:db8:10:3::1 description upstream-router-v6
 neighbor 2001:db8:10:4::1 remote-as 65001
 neighbor 2001:db8:10:4::1 description edge-router-v6
 !
 address-family ipv4 unicast
  neighbor 10.0.2.1 activate
  neighbor 10.0.2.1 soft-reconfiguration inbound
  neighbor 10.0.3.1 activate
  neighbor 10.0.3.1 soft-reconfiguration inbound
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2001:db8:10:3::1 activate
  neighbor 2001:db8:10:3::1 soft-reconfiguration inbound
  neighbor 2001:db8:10:4::1 activate
  neighbor 2001:db8:10:4::1 soft-reconfiguration inbound
 exit-address-family
exit
!
end
