frr defaults traditional
hostname internet
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.1.1/30
exit
!
router bgp 2121
 bgp router-id 10.0.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 neighbor 10.0.1.2 remote-as 65000
 neighbor 10.0.1.2 description upstream-router
 !
 address-family ipv4 unicast
  neighbor 10.0.1.2 activate
  neighbor 10.0.1.2 soft-reconfiguration inbound
 exit-address-family
 !
 bmp targets raven
  bmp stats interval 5000
  bmp monitor ipv4 unicast post-policy
  bmp connect 172.20.20.1 port 11019 min-retry 1000 max-retry 5000
 exit
exit
!
end
